    <header>
        <nav>
            <div class="logo">
                <a href="index.html"><img src="images/nav-img.png" alt="nav-img" class="nav-img"></a>
            </div>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li class="dropdown">
                    <button class="dropbtn"><a href="product.html">Products</a></button>
                    <div class="dropdown-content">
                        <a href="vacuum_robot.html">Vacuums</a>
                        <a href="lawnmower_robot.html">Lawn mowers</a>
                        <a href="pool_robot.html">Pool cleaners</a>
                    </div>
                </li>
                <li><a href="enquire.html">Enquire</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="enhancements.html">Enhancements</a></li>
            </ul> 
        </nav>
    </header>
