    <header>
        <nav>
            <div class="logo">
                <a href="index.php"><img src="images/nav-img.png" alt="nav-img" class="nav-img"></a>
            </div>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li class="dropdown">
                    <button class="dropbtn"><a href="product.php">Products</a></button>
                    <div class="dropdown-content">
                        <a href="vacuum_robot.php">Vacuums</a>
                        <a href="lawnmower_robot.php">Lawn mowers</a>
                        <a href="pool_robot.php">Pool cleaners</a>
                    </div>
                </li>
                <li><a href="enquire.php">Enquire</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="enhancements.php">Enhancements</a></li>
                <li><a href="signup.php">Enhancements</a></li>
                <li><a href="login.php">Enhancements</a></li>
            </ul> 
        </nav>
    </header>
